In [1]:
#################################################
# 1. Load Credentials from .env
#################################################

import os
from dotenv import load_dotenv
import requests
from requests.auth import HTTPBasicAuth
import pandas as pd

load_dotenv()

USER = os.getenv("DBREPO_USER")
PASSWORD = os.getenv("DBREPO_PASSWORD")

print("Credentials loaded.")

Credentials loaded.

In [2]:
#################################################
# 2. DBRepo Client Setup
#################################################

from dbrepo.RestClient import RestClient

BASE_URL = "https://test.dbrepo.tuwien.ac.at"

client = RestClient(
    BASE_URL,
    username=USER,
    password=PASSWORD
)

print("DBRepo client initialized.")

DBRepo client initialized.

In [3]:
#################################################
# 3. Validate Database and Existing Tables
#################################################

DB_NAME = "data_stew_grp22_air_quality"

databases = client.get_databases()

DB_ID = None

for db in databases:

    if db.name == DB_NAME:

        DB_ID = db.id

        print("Database found:")
        print("ID:", db.id)
        print("Name:", db.name)
        print("Internal Name:", db.internal_name)

        break

# Stop if DB does not exist
if DB_ID is None:

    raise Exception("Database not found.")

# Fetch tables
tables = client.get_tables(DB_ID)

print("\nExisting Tables:\n")

for table in tables:

    print("-", table.name)

# Validate required tables
required_tables = {
    "t_station",
    "t_time",
    "t_measurement"
}

existing_tables = {t.name for t in tables}

missing_tables = required_tables - existing_tables

if len(missing_tables) > 0:

    raise Exception(f"Missing tables: {missing_tables}")

print("\nAll required tables exist.")

Database found:
ID: 81d82941-cae0-4cba-b27d-1bd883dd713a
Name: data_stew_grp22_air_quality
Internal Name: data_stew_grp22_air_quality_gvui

Existing Tables:

- t_measurement
- t_time
- t_station

All required tables exist.

In [4]:
#################################################
# 4. Read SQL View Definitions
#################################################

from pathlib import Path

VIEWS_SQL_PATH = Path("../docs/views.sql")

# Check file exists
if not VIEWS_SQL_PATH.exists():

    raise Exception(f"views.sql not found at: {VIEWS_SQL_PATH}")

# Read SQL file
with open(VIEWS_SQL_PATH, "r") as file:

    views_sql = file.read()

print("views.sql loaded successfully.\n")

print(views_sql[:1000])

views.sql loaded successfully.

-- =========================================================
-- views.sql
-- Air Quality Data Stewardship Project
-- TU Wien - WP2 T2.4 View Definitions
-- =========================================================


-- =========================================================
-- Remove existing views if they already exist
-- =========================================================

DROP VIEW IF EXISTS vw_air_quality_features;

DROP VIEW IF EXISTS vw_daily_pollution_summary;

DROP VIEW IF EXISTS vw_station_pollution_summary;



-- =========================================================
-- View: vw_air_quality_features
-- Description:
-- Denormalized ML-ready feature table combining
-- measurements, temporal information, and station metadata.
-- =========================================================

CREATE VIEW vw_air_quality_features AS

SELECT
    m.measurement_id,

    s.station_id,
    s.station_name,
    s.latitude,
    s.longitude,

    t.time_id,
    t.date,
    t.hour,

In [13]:
#################################################
# 5. Create View: vw_air_quality_features
#################################################

from dbrepo.api.dto import QueryDefinition

# Refresh existing views
existing_views = client.get_views(DB_ID)

existing_view_names = {

    view.name

    for view in existing_views
}

VIEW_NAME = "vw_air_quality_features"

if VIEW_NAME in existing_view_names:

    print(f"{VIEW_NAME} already exists. Skipping.")

else:

    query_definition = QueryDefinition(

        columns=[

            "t_measurement.measurement_id",
            "t_measurement.station_id",
            "t_measurement.time_id",

            "t_measurement.so2",
            "t_measurement.no",
            "t_measurement.no2",
            "t_measurement.co",
            "t_measurement.pm10",
            "t_measurement.o3",
            "t_measurement.pm25",

            "t_measurement.wind_direction",
            "t_measurement.wind_speed",

            "t_measurement.temperature",
            "t_measurement.humidity",
            "t_measurement.pressure",
            "t_measurement.solar_radiation",
            "t_measurement.rain",

            "t_measurement.ben",
            "t_measurement.tol",
            "t_measurement.mxil"
        ],

        datasources=[
            "t_measurement"
        ]
    )

    created_view = client.create_view(

        DB_ID,

        VIEW_NAME,

        query=query_definition,

        is_public=False,

        is_schema_public=False
    )

    print("View created successfully.")

    print("View Name:", created_view.name)

    print("View ID:", created_view.id)

View created successfully.
View Name: vw_air_quality_features
View ID: d813aea7-7397-4821-9618-7922760ee604

In [14]:
#################################################
# 6. Validate Feature View
#################################################

views = client.get_views(DB_ID)

feature_view = None

for view in views:

    if view.name == "vw_air_quality_features":

        feature_view = view

        break

if feature_view is None:

    raise Exception("View not found.")

print("View ID:")

print(feature_view.id)

# Row count
count = client.get_view_data_count(

    DB_ID,

    feature_view.id
)

print("\nRows in view:")

print(count)

# Preview
df_view = client.get_view_data(

    DB_ID,

    feature_view.id,

    page=0,

    size=10
)

display(df_view)

View ID:
d813aea7-7397-4821-9618-7922760ee604

Rows in view:
43800

,pm25,measurement_id,o3,humidity,solar_radiation,time_id,mxil,wind_speed,pressure,no2,ben,no,so2,temperature,wind_direction,station_id,rain,pm10,tol,co
0,3.0,1,58.0,54.0,17.0,8737,0.40,1.13,1009.0,15.0,0.10,2.0,4.0,14.1,158.0,1,0.0,5.0,0.60,0.29
1,6.0,2,54.0,55.0,17.0,8738,0.60,0.48,1008.0,14.0,0.10,1.0,3.0,14.1,203.0,1,0.0,4.0,0.90,0.25
2,6.0,3,50.0,58.0,17.0,8739,1.88,0.10,1007.0,16.0,0.10,1.0,5.0,13.4,5.0,1,0.0,7.0,0.92,0.26
3,1.0,4,68.0,53.0,17.0,8740,3.20,0.75,1006.0,5.0,0.13,1.0,4.0,15.3,181.0,1,0.0,6.0,1.23,0.24
4,1.0,5,56.0,55.0,17.0,8741,0.63,0.78,1006.0,13.0,0.10,2.0,4.0,14.9,181.0,1,0.0,6.0,0.50,0.26
5,5.0,6,42.0,57.0,17.0,8742,0.60,0.32,1006.0,23.0,0.10,4.0,4.0,14.3,180.0,1,0.0,8.0,0.73,0.30
6,3.0,7,11.0,60.0,17.0,8743,1.27,0.10,1006.0,51.0,0.15,33.0,7.0,13.1,318.0,1,0.0,9.0,1.20,0.42
7,3.0,8,4.0,61.0,17.0,8744,1.70,0.10,1006.0,63.0,0.23,52.0,15.0,12.4,337.0,1,0.0,19.0,1.85,0.63
8,5.0,9,16.0,58.0,17.0,8745,2.45,1.05,1005.0,60.0,0.53,87.0,9.0,12.7,180.0,1,0.0,18.0,3.08,0.64
9,10.0,10,10.0,53.0,28.0,8746,2.72,0.12,1006.0,71.0,0.52,67.0,8.0,14.1,316.0,1,0.0,22.0,3.15,0.61

In [15]:
#################################################
# 7. Create View: vw_daily_pollution_summary
#################################################

from dbrepo.api.dto import QueryDefinition

VIEW_NAME = "vw_daily_pollution_summary"

# Refresh existing views
existing_views = client.get_views(DB_ID)

existing_view_names = {

    view.name

    for view in existing_views
}

if VIEW_NAME in existing_view_names:

    print(f"{VIEW_NAME} already exists. Skipping.")

else:

    query_definition = QueryDefinition(

        columns=[

            "t_measurement.time_id",

            "t_measurement.so2",
            "t_measurement.no",
            "t_measurement.no2",
            "t_measurement.co",
            "t_measurement.pm10",
            "t_measurement.o3",
            "t_measurement.pm25",

            "t_measurement.temperature",
            "t_measurement.humidity",
            "t_measurement.pressure"
        ],

        datasources=[
            "t_measurement"
        ]
    )

    created_view = client.create_view(

        DB_ID,

        VIEW_NAME,

        query=query_definition,

        is_public=False,

        is_schema_public=False
    )

    print("View created successfully.")

    print("View Name:", created_view.name)

    print("View ID:", created_view.id)

View created successfully.
View Name: vw_daily_pollution_summary
View ID: ef4a51eb-17cb-4fb9-b05d-01348d7188dd

In [16]:
#################################################
# 8. Validate View: vw_daily_pollution_summary
#################################################

views = client.get_views(DB_ID)

daily_view = None

for view in views:

    if view.name == "vw_daily_pollution_summary":

        daily_view = view

        break

if daily_view is None:

    raise Exception("View not found.")

print("View ID:")

print(daily_view.id)

# Row count
count = client.get_view_data_count(

    DB_ID,

    daily_view.id
)

print("\nRows in view:")

print(count)

# Preview
df_daily_view = client.get_view_data(

    DB_ID,

    daily_view.id,

    page=0,

    size=10
)

display(df_daily_view)

View ID:
ef4a51eb-17cb-4fb9-b05d-01348d7188dd

Rows in view:
43800

,pm25,o3,humidity,time_id,pressure,no2,no,so2,temperature,pm10,co
0,3.0,58.0,54.0,8737,1009.0,15.0,2.0,4.0,14.1,5.0,0.29
1,6.0,54.0,55.0,8738,1008.0,14.0,1.0,3.0,14.1,4.0,0.25
2,6.0,50.0,58.0,8739,1007.0,16.0,1.0,5.0,13.4,7.0,0.26
3,1.0,68.0,53.0,8740,1006.0,5.0,1.0,4.0,15.3,6.0,0.24
4,1.0,56.0,55.0,8741,1006.0,13.0,2.0,4.0,14.9,6.0,0.26
5,5.0,42.0,57.0,8742,1006.0,23.0,4.0,4.0,14.3,8.0,0.30
6,3.0,11.0,60.0,8743,1006.0,51.0,33.0,7.0,13.1,9.0,0.42
7,3.0,4.0,61.0,8744,1006.0,63.0,52.0,15.0,12.4,19.0,0.63
8,5.0,16.0,58.0,8745,1005.0,60.0,87.0,9.0,12.7,18.0,0.64
9,10.0,10.0,53.0,8746,1006.0,71.0,67.0,8.0,14.1,22.0,0.61

In [17]:
#################################################
# 9. Create View: vw_station_pollution_summary
#################################################

from dbrepo.api.dto import QueryDefinition

VIEW_NAME = "vw_station_pollution_summary"

# Refresh existing views
existing_views = client.get_views(DB_ID)

existing_view_names = {

    view.name

    for view in existing_views
}

if VIEW_NAME in existing_view_names:

    print(f"{VIEW_NAME} already exists. Skipping.")

else:

    query_definition = QueryDefinition(

        columns=[

            "t_measurement.station_id",

            "t_measurement.so2",
            "t_measurement.no",
            "t_measurement.no2",
            "t_measurement.co",
            "t_measurement.pm10",
            "t_measurement.o3",
            "t_measurement.pm25",

            "t_measurement.temperature",
            "t_measurement.humidity",
            "t_measurement.pressure",

            "t_measurement.wind_speed",
            "t_measurement.wind_direction"
        ],

        datasources=[
            "t_measurement"
        ]
    )

    created_view = client.create_view(

        DB_ID,

        VIEW_NAME,

        query=query_definition,

        is_public=False,

        is_schema_public=False
    )

    print("View created successfully.")

    print("View Name:", created_view.name)

    print("View ID:", created_view.id)

View created successfully.
View Name: vw_station_pollution_summary
View ID: 0cb0c0e4-1a44-4b03-8b4e-763292bba56a

In [18]:
#################################################
# 10. Validate View: vw_station_pollution_summary
#################################################

views = client.get_views(DB_ID)

station_view = None

for view in views:

    if view.name == "vw_station_pollution_summary":

        station_view = view

        break

if station_view is None:

    raise Exception("View not found.")

print("View ID:")

print(station_view.id)

# Row count
count = client.get_view_data_count(

    DB_ID,

    station_view.id
)

print("\nRows in view:")

print(count)

# Preview
df_station_view = client.get_view_data(

    DB_ID,

    station_view.id,

    page=0,

    size=10
)

display(df_station_view)

View ID:
0cb0c0e4-1a44-4b03-8b4e-763292bba56a

Rows in view:
43800

,pm25,humidity,wind_speed,pressure,no,co,o3,no2,so2,temperature,wind_direction,station_id,pm10
0,3.0,54.0,1.13,1009.0,2.0,0.29,58.0,15.0,4.0,14.1,158.0,1,5.0
1,6.0,55.0,0.48,1008.0,1.0,0.25,54.0,14.0,3.0,14.1,203.0,1,4.0
2,6.0,58.0,0.10,1007.0,1.0,0.26,50.0,16.0,5.0,13.4,5.0,1,7.0
3,1.0,53.0,0.75,1006.0,1.0,0.24,68.0,5.0,4.0,15.3,181.0,1,6.0
4,1.0,55.0,0.78,1006.0,2.0,0.26,56.0,13.0,4.0,14.9,181.0,1,6.0
5,5.0,57.0,0.32,1006.0,4.0,0.30,42.0,23.0,4.0,14.3,180.0,1,8.0
6,3.0,60.0,0.10,1006.0,33.0,0.42,11.0,51.0,7.0,13.1,318.0,1,9.0
7,3.0,61.0,0.10,1006.0,52.0,0.63,4.0,63.0,15.0,12.4,337.0,1,19.0
8,5.0,58.0,1.05,1005.0,87.0,0.64,16.0,60.0,9.0,12.7,180.0,1,18.0
9,10.0,53.0,0.12,1006.0,67.0,0.61,10.0,71.0,8.0,14.1,316.0,1,22.0